name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Python

      # - name: Install dependencies

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version
        id: vars
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV


      - name: Building and Pushing API Images
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }}

      - name: Building and Pushing WEB image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-web:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-web:${{ github.sha }}


      - name: Setup kubectl using KUBECONFIG secret
        run: |
          mkdir -p  $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to the cluster
        run: |
          kubectl apply -f k8s/

